version: '3'

services:
  mongo_container:
    image: mongo
    restart: always

  adminMongo_container:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongo_container
    networks:
      - practica_net
  
  backend_container:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mongo_container
    networks:
      - practica_net

  frontend_container:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend_container
    networks:
      - practica_net

  nginx_container:
    image: nginx
    restart: always
    volumes:
      - ./loadbalancer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend_container
      - backend_container
    networks:
      - practica_net

  prometheus_container:
    image: prom/prometheus:v2.20.1
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - practica_net

  grafana_container:
    image: grafana/grafana:7.1.5
    volumes:
      - myGrafanaVol:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3500:3000"
    depends_on:
      - prometheus_container
    networks:
      - practica_net

networks:
  practica_net:
    driver: bridge

volumes:
  myGrafanaVol:
